src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * User
 *
 * @ORM\Table(name="user", uniqueConstraints={@ORM\UniqueConstraint(name="UNIQ_8D93D64986CC499D", columns={"pseudo"})}, indexes={@ORM\Index(name="role_id", columns={"role_id"}), @ORM\Index(name="space_id", columns={"space_id"})})
 * @ORM\Entity
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="pseudo", type="string", length=180, nullable=false)
     */
    private $pseudo;

    /**
     * @var array
     *
     * @ORM\Column(name="roles", type="json", nullable=false)
     */
    private $roles;

    /**
     * @var string The hashed password
     * @ORM\Column(name="password", type="string", length=255, nullable=false)
     */
    private $password;

    /**
     * @var string
     *
     * @ORM\Column(name="first_name", type="string", length=50, nullable=false)
     */
    private $firstName;

    /**
     * @var string
     *
     * @ORM\Column(name="last_name", type="string", length=50, nullable=false)
     */
    private $lastName;

    /**
     * @var string
     *
     * @ORM\Column(name="gender", type="string", length=50, nullable=false)
     */
    private $gender;

    /**
     * @var string
     *
     * @ORM\Column(name="pronoun", type="string", length=50, nullable=false)
     */
    private $pronoun;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="dob", type="date", nullable=false)
     */
    private $dob;

    /**
     * @var string
     *
     * @ORM\Column(name="first_mail", type="string", length=100, nullable=false)
     */
    private $firstMail;

    /**
     * @var string|null
     *
     * @ORM\Column(name="second_mail", type="string", length=100, nullable=true)
     */
    private $secondMail;

    /**
     * @var string
     *
     * @ORM\Column(name="adress", type="string", length=100, nullable=false)
     */
    private $adress;

    /**
     * @var string
     *
     * @ORM\Column(name="zip", type="string", length=5, nullable=false)
     */
    private $zip;

    /**
     * @var string
     *
     * @ORM\Column(name="city", type="string", length=50, nullable=false)
     */
    private $city;

    /**
     * @var string
     *
     * @ORM\Column(name="phone", type="string", length=10, nullable=false)
     */
    private $phone;

    /**
     * @var string
     *
     * @ORM\Column(name="member_status", type="string", length=100, nullable=false)
     */
    private $memberStatus;

    /**
     * @var bool
     *
     * @ORM\Column(name="ca", type="boolean", nullable=false)
     */
    private $ca;

    /**
     * @var string
     *
     * @ORM\Column(name="shirt_size", type="string", length=10, nullable=false)
     */
    private $shirtSize;

    /**
     * @var string
     *
     * @ORM\Column(name="fav_color", type="string", length=50, nullable=false)
     */
    private $favColor;

    /**
     * @var string
     *
     * @ORM\Column(name="fav_games", type="string", length=255, nullable=false)
     */
    private $favGames;

    /**
     * @var string|null
     *
     * @ORM\Column(name="comments", type="string", length=255, nullable=true)
     */
    private $comments;

    /**
     * @var \Workspaces
     *
     * @ORM\ManyToOne(targetEntity="Workspaces")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="space_id", referencedColumnName="id")
     * })
     */
    private $space;

    /**
     * @var \Roles
     *
     * @ORM\ManyToOne(targetEntity="Roles")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="role_id", referencedColumnName="id")
     * })
     */
    private $role;

    // setters and getters come next (for some reason Symfony didn't generate them I had to do it manually, probably because I make:crud on User before finishing the database?)

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;
        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;
        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): self
    {
        $this->gender = $gender;
        return $this;
    }

    public function getPronoun(): ?string
    {
        return $this->pronoun;
    }

    public function setPronoun(string $pronoun): self
    {
        $this->pronoun = $pronoun;
        return $this;
    }

    public function getDob(): ?string
    {
        return $this->dob;
    }

    public function setDob(string $dob): self
    {
        $this->dob = $dob;
        return $this;
    }

    public function getFirstMail(): ?string
    {
        return $this->firstMail;
    }

    public function setFirstMail(string $firstMail): self
    {
        $this->firstMail = $firstMail;
        return $this;
    }

    public function getSecondMail(): ?string
    {
        return $this->secondMail;
    }

    public function setSecondMail(string $secondMail): self
    {
        $this->secondMail = $secondMail;
        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;
        return $this;
    }

    public function getZip(): ?string
    {
        return $this->zip;
    }

    public function setZip(string $zip): self
    {
        $this->zip = $zip;
        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;
        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;
        return $this;
    }

    public function getMemberStatus(): string
    {
        return $this->memberStatus;
    }

    public function setMemberStatus(string $memberStatus): self
    {
        $this->memberStatus = $memberStatus;
        return $this;
    }

    public function getCa(): ?boolean
    {
        return $this->ca;
    }

    public function setCa(boolean $ca): self
    {
        $this->ca = $ca;
        return $this;
    }

    public function getShirtSize(): ?string
    {
        return $this->shirtSize;
    }

    public function setShirtSize(string $shirtSize): self
    {
        $this->shirtSize = $shirtSize;
        return $this;
    }

    public function getFavColor(): ?string
    {
        return $this->favColor;
    }

    public function setFavColor(string $favColor): self
    {
        $this->favColor = $favColor;
        return $this;
    }

    public function getFavGames(): ?string
    {
        return $this->favGames;
    }

    public function setFavGames(string $favGames): self
    {
        $this->favGames = $favGames;
        return $this;
    }

    public function getComments(): ?string
    {
        return $this->comments;
    }

    public function setComments(string $comments): self
    {
        $this->comments = $comments;
        return $this;
    }

    public function getSpace(): ?int
    {
        return $this->space;
    }

    public function setSpace(int $space): self
    {
        $this->space = $space;
        return $this;
    }

    public function getRole(): ?int
    {
        return $this->role;
    }

    public function setRole(int $role): self
    {
        $this->role = $role;
        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->pseudo;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->pseudo;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

src/Controller/DashboardController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Tasks;
use App\Entity\Notes;
use App\Repository\UserRepository;
use App\Repository\TasksRepository;
use App\Repository\NotesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DashboardController extends AbstractController
{
//------------------------------------------------------------------ RENDERING THE INDEX (DASHBOARD) -----------------------------------------------------------------------//
    /**
     * @Route("/dashboard", name="dashboard")
     */
    public function index(TasksRepository $task_repo, NotesRepository $note_repo): Response
    {
        //declaring my variables
        $user = $this->getUser();
        $task = $task_repo->findAll();
        $note = $note_repo->findAll();
        //simple return statement to render a view, we choose to render the file index.html.twig that is stored in the dashboard directory
        return $this->render('dashboard/index.html.twig', [
            //now we define variables and their value, so we can call them in the twig file that is asked to be rendered above
            'user' => $user,
            'task' => $task,
            'note' => $note
        ]
    );
    }
    //-------------------------------------------------------------- RENDERING THE DIFFERENT WORKSPACES --------------------------------------------------------------------//
    // ------ planning ------ //
    /**
     * @Route("/planning", name="planning")
     */
    public function planning(UserRepository $user_repo) {
        $user = $this->getUser();
        return $this->render('dashboard/planning.html.twig', [
            'user' => $user
        ]);
    }
    // ------ administration ------ //
    /**
     * @Route("/admin", name="admin")
     */
    public function admin(UserRepository $user_repo) {
        $user = $this->getUser();
        return $this->render('dashboard/admin.html.twig', [
            'user' => $user
        ]);
    }
    // ------ human ressources ------ //
    /**
     * @Route("/rh", name="rh")
     */
    public function rh(UserRepository $user_repo) {
        $user = $this->getUser();
        return $this->render('dashboard/rh.html.twig', [
            'user' => $user,
            'users' => $user_repo->findAll()
        ]);
    }
    // ------ marketing ------ //
    /**
     * @Route("/marketing", name="marketing")
     */
    public function marketing(UserRepository $user_repo) {
        $user = $this->getUser();
        return $this->render('dashboard/marketing.html.twig', [
            'user' => $user
        ]);
    }
    // ------ communication ------ //
    /**
     * @Route("/comm", name="comm")
     */
    public function comm(UserRepository $user_repo) {
        $user = $this->getUser();
        return $this->render('dashboard/comm.html.twig', [
            'user' => $user
        ]);
    }
    // ------ event ------ //
    /**
     * @Route("/event", name="event")
     */
    public function event(UserRepository $user_repo) {
        $user = $this->getUser();
        return $this->render('dashboard/event.html.twig', [
            'user' => $user
        ]);
    }
    // ------ webtv ------ //
    /**
     * @Route("/webtv", name="webtv")
     */
    public function webtv(UserRepository $user_repo) {
        $user = $this->getUser();
        return $this->render('dashboard/webtv.html.twig', [
            'user' => $user
        ]);
    }
    // ------ community ------ //
    /**
     * @Route("/community", name="community")
     */
    public function community(UserRepository $user_repo) {
        $user = $this->getUser();
        return $this->render('dashboard/community.html.twig', [
            'user' => $user
        ]);
    }
    // ------ GTSport ------ //
    /**
     * @Route("/gtsport", name="gtsport")
     */
    public function gtsport(UserRepository $user_repo) {
        $user = $this->getUser();
        return $this->render('dashboard/gtsport.html.twig', [
            'user' => $user
        ]);
    }
    // ------ Dofus ------ //
    /**
     * @Route("/dofus", name="dofus")
     */
    public function dofus(UserRepository $user_repo) {
        $user = $this->getUser();
        return $this->render('dashboard/dofus.html.twig', [
            'user' => $user
        ]);
    }
    // ------ FIFA ------ //
    /**
     * @Route("/fifa", name="fifa")
     */
    public function fifa(UserRepository $user_repo) {
        $user = $this->getUser();
        return $this->render('dashboard/fifa.html.twig', [
            'user' => $user
        ]);
    }
    // ------ League of Legends ------ //
    /**
     * @Route("/lol", name="lol")
     */
    public function lol(UserRepository $user_repo) {
        $user = $this->getUser();
        return $this->render('dashboard/lol.html.twig', [
            'user' => $user
        ]);
    }
    // // ------ homepage ------ //
    // /**
    //  * @Route("/", name="home")
    //  */
    // public function home() {
    //     //this is my homepage
    //     return $this->render('dashboard/home.html.twig', [
    //         'title' => 'Connectez-vous pour accèder au panel'
    //     ]);
    // }
}

templates/dashboard/admin.html.twig
{% extends 'base.html.twig' %}
{% block body %}
{% endblock %}

templates/dashboard/comm.html.twig
{% extends 'base.html.twig' %}
{% block body %}
{% endblock %}

templates/dashboard/community.html.twig
{% extends 'base.html.twig' %}
{% block body %}
{% endblock %}

templates/dashboard/dofus.html.twig
{% extends 'base.html.twig' %}
{% block body %}
{% endblock %}

templates/dashboard/event.html.twig
{% extends 'base.html.twig' %}
{% block body %}
{% endblock %}

templates/dashboard/fifa.html.twig
{% extends 'base.html.twig' %}
{% block body %}
{% endblock %}

templates/dashboard/gtsport.html.twig
{% extends 'base.html.twig' %}
{% block body %}
{% endblock %}

templates/dashboard/home.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="https://i.ibb.co/C5vBpJw/9.png">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
        <link rel="stylesheet" type="text/css" href="/base.css"></link>
        <link rel="stylesheet" type="text/css" href="/nav.css"></link>
        <link rel="stylesheet" type="text/css" href="/index.css"></link>
        <link rel="stylesheet" type="text/css" href="/dashboard.css"></link>
        <link href="https://fonts.googleapis.com/css2?family=Exo:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
<main class="main-index">
    <!-- ------------------------------- TITLE -------------------------------- -->
    <div class="logo-title">
        <img src="/images/white_logo.png" alt="logo" id="logo">
        <h1 id="title">Bonjour Zephyrien !</h1>
    </div>

    <br>
    <h2 id="subtitle">Connecte toi pour accèder à ton panel :</h2>

    <!-- --------------------------- CONNECTION BOX --------------------------- -->
    <div class="outest-box">
    <div class="inner-box">
    <form method="post">

    {% if app.user %}
        <div class="signin">
            Vous êtes déjà connecté {{ app.user.username }}, <a href="{{ path('app_logout') }}">Me déconnecter</a>
        </div>
    {% endif %}

    <div class="signin">
        <div class="signin-field">
            <label for="inputPseudo">Pseudo</label>
            <input type="text" value="{{ last_username }}" name="pseudo" id="inputPseudo" class="form-control" autocomplete="username" required autofocus>
        </div>
            <div class="signin-field">
            <label for="inputPassword">Password</label>
        <input type="password" name="password" id="inputPassword" class="form-control" autocomplete="current-password" required>
        </div>
        <input type="hidden" name="_csrf_token"
            value="{{ csrf_token('authenticate') }}"
        >

        <div class="signin-field">
            <label>
                <input type="checkbox" name="_remember_me"> Remember me
            </label>
        </div>
        <div class="signin-field">
            <button class="btn btn-lg btn-primary" type="submit">
                Sign in
            </button>
        </div>
    </div>
</form>
    </div>
    </div>
</main>
    </body>
    <!-- ICONS -->
<script src="https://kit.fontawesome.com/94afbe7ce0.js" crossorigin="anonymous"></script>
<script src="https://unpkg.com/boxicons@2.0.9/dist/boxicons.js"></script>
</html>

templates/dashboard/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bienvenue sur ton Dashboard !{% endblock %}

{% block body %}
<div class="calendar-box">
    <div class="calendar">
    </div>
    <div class="new-task">
        <a class="new-task" href="{{ path('tasks_new') }}">Ajouter une tâche</a>
    </div>
</div>
<div class="tasks">
{% for task in task %}
    <div class="taskbox">
        <div class="task-title">
            {{ task.taskName }}
        </div>
        <div class="task-start">
            Du <span class="start">{{ task.taskStart | date('d/m/Y') }}</span>
            au <span class="end">{{ task.taskDeadline | date('d/m/Y') }}</span>
        </div>
        <div class="task-desc">
            {{ task.taskDesc }}
        </div>
        <div class="task-users">
            {{ task.taskUsers }}
        </div>
    </div>
{% endfor %}

</div>
<div class="notes-bigbox">
    <p class="box-title">MES DERNIÈRES NOTES</p>
    <div class="notes">
        {% for note in note %}
        <div class="notebox">
            <div class="note-title">
                {{ note.noteName }}
            </div>
            <div class="note-desc">
                {{ note.noteContent }}
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<div class="toolbox">
    <div></div>
</div>
{% endblock %}

templates/dashboard/lol.html.twig
{% extends 'base.html.twig' %}
{% block body %}
{% endblock %}

templates/dashboard/marketing.html.twig
{% extends 'base.html.twig' %}
{% block body %}
{% endblock %}

templates/dashboard/planning.html.twig
{% extends 'base.html.twig' %}
{% block body %}
{% endblock %}

templates/dashboard/rh.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<table>
  <tr>
    <th>Pseudo</th>
    <th>Password</th>
    <th>Autorisation</th>
  </tr>
  {% for user in users %}
  <tr>
    <td>{{ user.pseudo }}</td>
    <td>{{ user.password }}</td>
    <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
    <td>
        <a href="{{ path('user_show', {'id': user.id}) }}">show</a>
        <a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>
    </td>
  </tr>
  {% endfor %}
</table>
{% endblock %}

templates/dashboard/webtv.html.twig
{% extends 'base.html.twig' %}
{% block body %}
{% endblock %}